### ISSUE TITLE
Add Crypto class

### ISSUE THREAD

**Issue by ChibiFR** [ChibiFR/martine#8]
In src/Helpers, the php path should be Martine\Helpers\Crypto.
This class should allow crypting and testing equality of two crypted datas. See the native crypting functions of PHP.
This uses a salt that's generated randomly for each new Martine project you create. If no salt is available yet, hard code one in your unit testings.

```php
// Martine\Helpers\Crypto (src/Helpers/Crypto.php)

public __construct (string $appKey) // $appKey is used as salt
public string encrypt (string $str)
public bool equals (string $knowStr, string $cryptedStr)

```

**Comment by KylianLM** [comment]
src/Helpers (Martine\Helpers\Crypto) or src/Utils (Martine\Utils\Crypto) ?
@ChibiFR

**Comment by ChibiFR** [comment]
Martine\Helpers\Crypto (src/Helpers/Crypto.php)
Updated issue's comment
